name       : docker-credentials-secretservice
version    : 0.6.1
release    : 1
source     :
    - https://github.com/docker/docker-credential-helpers/archive/v0.6.1.tar.gz : 9b36ae15d5bceaaf3496b80413acafa6325c633af3ae211ce10724dfa7046883
license    : MIT
component  : virt
summary    : docker-credential-helpers is a suite of programs to use native stores to keep Docker credentials safe.
description: |
    docker-credential-helpers is a suite of programs to use native stores to keep Docker credentials safe.
builddeps  :
    - golang
    - pkgconfig(libsecret-1)
environment: GOPATH=$HOME/go
setup      : |
    mkdir -p $GOPATH/src/github.com/docker/docker-credential-helpers
    mv $workdir/* $GOPATH/src/github.com/docker/docker-credential-helpers/
build      : |
    cd $GOPATH/src/github.com/docker/docker-credential-helpers/
    %make secretservice
install    : |
    install -Dm 0755 $GOPATH/src/github.com/docker/docker-credential-helpers/bin/docker-credential-secretservice $installdir/usr/bin/docker-credentials-secretservice
