name       : docker-credentials-secretservice
version    : 0.6.2
release    : 2
source     :
    - https://github.com/docker/docker-credential-helpers/archive/v0.6.2.tar.gz : 1b332d40e3d50ce084e54feea09750e18c87dadcfdfd2e8e9bd4622cbbf461b2
license    : MIT
component  : virt
summary    : docker-credential-helpers is a suite of programs to use native stores to keep Docker credentials safe.
description: |
    docker-credential-helpers is a suite of programs to use native stores to keep Docker credentials safe.
builddeps  :
    - golang
    - pkgconfig(libsecret-1)
environment: GOPATH=$HOME/go
setup      : |
    mkdir -p $GOPATH/src/github.com/docker/docker-credential-helpers
    mv $workdir/* $GOPATH/src/github.com/docker/docker-credential-helpers/
build      : |
    cd $GOPATH/src/github.com/docker/docker-credential-helpers/
    %make secretservice
install    : |
    install -Dm 0755 $GOPATH/src/github.com/docker/docker-credential-helpers/bin/docker-credential-secretservice $installdir/usr/bin/docker-credentials-secretservice
